lesson 2: changed file contacts and added translate
Mihail-tec/webix-jet-start pull request #2
Opened 2022-04-19 07:12 UTC by Mihail-tec

2022-04-19 07:41 UTC, AlexeyXB requested changes

2022-04-19 07:41 UTC, AlexeyXB commented on sources/views/components/autoForm.js
> +		config.fields.map(el => config.elements.push({view: "text", label: _(el), name: el, invalidMessage: "Is not be empty"}));
Здесь не хватает перевода

2022-04-19 07:41 UTC, AlexeyXB commented on sources/views/components/datatable.js
> +						webix.confirm(_("Are you sure?")).then(() => {
Нужно добавить переводы для ok, cancel

2022-04-19 07:41 UTC, AlexeyXB commented on sources/views/components/autoForm.js
> +		const _ = this.$scope.app.getService("locale")._;
Лучше вынести локализацию из этого `proto`, а переводы прикидывать напрямую в конфиг. Например:
`config.saveLabel`, `config.cancelLabel`,` config.defaultInvalidMessage`.

2022-04-19 07:41 UTC, AlexeyXB commented on sources/views/contacts/form.js
> +		const form = this.$$("form");
Можно создать `this.form = this.$$("form");` и в последующем обращаться к `this.form` для получения формы.

2022-04-19 07:41 UTC, AlexeyXB commented on sources/views/contacts/list.js
> +		const list = this.$$("list");
Аналогично форме из предыдущего файла здесь можно сделать обертку для листа
`this.list = this.$$("list");`

2022-04-19 07:41 UTC, AlexeyXB commented on sources/views/contacts/list.js
> +		const id = this.getParam("id");
Я думаю, эту логику лучше вынести в `urlChange`

2022-04-19 07:41 UTC, AlexeyXB commented on sources/views/contacts/list.js
> +			view.$scope.app.show(`top/contacts?id=${lastId}`);
`view.$scope` => `this`

2022-04-19 09:57 UTC, AlexeyXB approved these changes

2022-04-19 16:39 UTC, HelgaListopad requested changes

2022-04-19 16:39 UTC, HelgaListopad commented on sources/views/contacts/form.js
> +		const correctEmail = _("Write correct email");
Я бы не выносила все эти константы
Как правило, локализация применяется "на месте" и должна сокращать количество строк кода.)
```js
invalidMessage:  _("Write correct email");
```

2022-04-19 16:39 UTC, HelgaListopad commented on sources/views/contacts/list.js
> +		const id = this.getParam("id");
Я бы предложила оставить именно это на init (он [срабатывает раньше](https://webix.gitbook.io/webix-jet/api/jetview-api/jetview-handlers#ready) urlChange), а через urlChange обработать другой случай.
Юзер может удалить из адресной строки параметр, и сейчас получается, что тогда
- в листе селектится первая строка
- форма заполняется данными
- в URL параметра нет

Это всё не очень хорошо

Второй случай, когда параметра URL может не быть - если юзер нажал Cancel в форме
Тогда нужно не только очистить форму и сбросить селект листа, но и зачистить параметр.

2022-04-19 16:39 UTC, HelgaListopad commented on sources/views/contacts/list.js
> +		const id = this.getParam("id");
При этом часть кода ниже (проверку на `.exists(id)`) есть смысл оставить здесь как "защиту" от неправильных параметров.
Но если есть коллекция, не нужно брать `view.data.getFirstId`
Лучше 
```
else if (!contactsCollection.exists(id)) {
	const firstId = contactsCollection.getFirstId();
	view.select(firstId, false);
}
```

2022-04-19 16:39 UTC, HelgaListopad commented on sources/views/contacts/list.js
> +			this.list.unselectAll();
Параметр URL тоже нужно здесь почистить

2022-04-19 16:39 UTC, HelgaListopad commented on sources/views/settings.js
> +		const languag = _("Language");
Здесь (в целом, везде) локализацию я бы тоже не выносила в переменные

2022-04-20 10:04 UTC, HelgaListopad approved these changes

2022-04-20 10:04 UTC, merged