lesson 3: added server
Mihail-tec/webix-jet-start pull request #3
Opened 2022-04-20 12:23 UTC by Mihail-tec

2022-04-20 14:41 UTC, AlexeyXB requested changes

2022-04-20 14:41 UTC, AlexeyXB commented on sources/views/server/url.js
> +	pathCountries:	"/api/v1/countries/",
У тебя в проекте не используются `pathCountries`, `pathCtatuses`, `pathContacts`.

2022-04-20 14:41 UTC, AlexeyXB commented on sources/views/components/datatable.js
> +				.filter(x => x.id).map(x => x.id)
Это можно сделать за один проход filter и один map

2022-04-20 14:41 UTC, AlexeyXB commented on sources/views/components/datatable.js
> +							data.waitSave(() => {
Стоит добавить `catch` для отката и сообщения об ошибке, в случае если на сервере не произошло сохранение данных.

2022-04-20 14:41 UTC, AlexeyXB commented on sources/views/contacts/form.js
> +			contactsCollection.waitSave(() => {
Здесь тоже просится `catch`.

2022-04-22 10:09 UTC, HelgaListopad approved these changes

2022-04-22 10:12 UTC, AlexeyXB approved these changes

2022-04-22 10:12 UTC, merged